### ISSUE TITLE
setSectionIndexer in FastScrollRecyclerView

### ISSUE THREAD

**Issue by mkutlev** [L4Digital/FastScroll#13]
Could you add setSectionIndexer to FastScrollRecyclerView?
I use common adapter for all screens and because of this limitation I have to extend the adapter for all screens I have to use the library:

     public void setSectionIndexer(FastScroller.SectionIndexer sectionIndexer) {
         mFastScroller.setSectionIndexer(sectionIndexer);
     }

**Comment by randr0id** [comment]
This has been added in commit [bdd05dd](https://github.com/L4Digital/FastScroll/commit/bdd05dde37c8753d3d6abe24945d71588ce0ad5b) and released in [1.0.3](https://github.com/L4Digital/FastScroll/releases/tag/1.0.3).
