### ISSUE TITLE
how to use with SwipeRefreshLayout?

### ISSUE THREAD

**Issue by Junediff** [L4Digital/FastScroll#14]
I can't use inside SwipdeRefreshLayout, because cant drag FastScroll.
When I do action drag FastScrollbar, refresh action begin.

<android.support.v4.widget.SwipeRefreshLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_below="@+id/fragCardlist_divider"
            android:id="@+id/fragCardlist_swipe"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            >
            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <com.l4digital.fastscroll.FastScrollRecyclerView
                    android:id="@+id/recycler_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:bubbleColor="@color/viewpager_underline"
                    app:bubbleTextColor="@color/white"
                    app:handleColor="@color/viewpager_underline"
                    app:hideScrollbar="false"
                    app:showTrack="false"
                    />
            </FrameLayout>
        </android.support.v4.widget.SwipeRefreshLayout>

**Comment by Junediff** [comment]
I found issue Not supported SwipeRefreshLayout with RecyclerView #7,
but i can't solve my problem.

**Comment by randr0id** [comment]
You can disable the `SwipeRefreshLayout` while fast scrolling:
```java
recyclerView.setFastScrollStateChangeListener(new FastScrollStateChangeListener() {

            @Override
            public void onFastScrollStart() {
                refreshLayout.setEnabled(false);
            }

            @Override
            public void onFastScrollStop() {
                refreshLayout.setEnabled(true);
            }
        });
```
