### ISSUE TITLE
Scroll handle and bubble by default touched with toolbar

### ISSUE THREAD

**Issue by sam4444** [L4Digital/FastScroll#15]
Can you provide option so with that i can set handle by default position with distance of toolbar. Please once see in WhatsApp. There are almost 10 - 15 dp space between toolbar and scroll handle by default. If possible then please provide something like this option.

**Comment by randr0id** [comment]
This is a good suggestion and we will plan to add a top/bottom margin in the future (possibly configurable).

In the meantime, this can be done now by implementing `FastScroller` in xml and adding a top/bottom margin. Take a look at #4 for an example.

**Comment by sam4444** [comment]
@randr0id thank you so much for your positive support and provide me useful solution for right now.

**Comment by randr0id** [comment]
Fixed in commit f78732a and released in 1.0.4
