### ISSUE TITLE
Auto hide for scrollbar

### ISSUE THREAD

**Issue by motis10** [L4Digital/FastScroll#16]
Is there any support in auto-hide scroll bar?
I mean, if user touch the scrollbar area show it otherwise hide it with animation (what happens in native dialer app)?

**Comment by randr0id** [comment]
Yes, auto-hide is already supported and the behavior is similar to the dialer app.

**Comment by motis10** [comment]
How should I enable it?

**Comment by randr0id** [comment]
It is always enabled. There is an example Activity in this project that you can run to see a demo.

**Comment by motis10** [comment]
Great!!! thank you very much.
