### ISSUE TITLE
Separate padding left|top|right|bottom 

### ISSUE THREAD

**Issue by chiara-pugno** [L4Digital/FastScroll#19]
I need of distinguishing between padding left and other paddings of fastscroll.
Now all paddings have the same value : fastscroll_scrollbar_padding.

Can you separate them with for example
fastscroll_scrollbar_padding_left
fastscroll_scrollbar_padding_top
ecc...?

Thanks

**Comment by randr0id** [comment]
Fixed in commit f78732a and released in 1.0.4
