### ISSUE TITLE
when using linearLayoutManager.setStackFromEnd(true) fastscroller shows scrollbar at top (should show at bottom)

### ISSUE THREAD

**Issue by zoff99** [L4Digital/FastScroll#20]
i use: linearLayoutManager.setStackFromEnd(true)
and also always scroll to bottom, when first showing the view (containing messages).

at first start the scrollbar shows at top position, which is wrong in this case (because view is scrolled all the way down).
when i scroll a little, it fixes itself and show correctly at bottom position.

can you fix it?

**Comment by randr0id** [comment]
I will look into fixing this.

**Comment by zoff99** [comment]
@randr0id super. do you have enough info? do you see the bug?

**Comment by randr0id** [comment]
Fixed in commit ab7b4db and will be released in version 1.0.5

**Comment by TonyHaddad91** [comment]
@randr0id are you going to release 1.1.0 any soon?

**Comment by randr0id** [comment]
Yes @TonyHaddad91. I've been waiting for ConstraintLayout 1.1.0 to be released so that I can ensure compatibility. It is currently at `beta5` and I expect it will be released soon, but I've been expecting that for months.
