### ISSUE TITLE
Problems with a right navigation view in a drawerlayout

### ISSUE THREAD

**Issue by franciscojunior** [L4Digital/FastScroll#21]
Hi! Thank you for such a great library! It works great but I'm facing a problem when using it in a activity which has a drawer layout with a navigation view which opens from the right.

When I try to scroll using the handle, most of the time, the scroll stops suddenly while my finger still is touching the screen and the right navigation view starts to open. 

Also, when I have the showtrack property set to true, start a scroll and try to touch the track, it also doesn't work well. 

While writing this report, I decided to use the padding support you added based on #15 and it seemed to make the behaviour much better as it doesn't compete with the right navigation view.

I decided to open this issue anyway because it would be very good if you could check this out. Maybe disable the touch processing of the parent view when handling track and handle touch. 

Thanks for any advice.

**Comment by randr0id** [comment]
Thanks for the detailed report. This should be fixed in commit 51f2cb9 and will be released in 1.0.5
