### ISSUE TITLE
Scrollbar snaps to top 

### ISSUE THREAD

**Issue by doerschner** [L4Digital/FastScroll#22]
Hey,
great library so far, way better than most that I used before! 
But i got a problem with the UI-Handle. Sometimes it snaps back to the top. It seems the problem occurs when I release while dragging or some kind of swipe motion in generel. The handle snaps back to top then, the position inside the recyclerview is correct though.
Also, when I scroll my recyclerview, the handle snaps back to the top. 

I use a custom layout manager which is not a derivation of LinearLayoutManager.

**Comment by randr0id** [comment]
I just pushed some changes that may fix this issue. Can you test and verify? If not, please provide more details as I’m unable to reproduce the issue. Code examples would also be helpful.
