### ISSUE TITLE
Conflict with other libraries in same parent layout 

### ISSUE THREAD

**Issue by Radiokot** [L4Digital/FastScroll#23]
**Problem**
For the same RecyclerView I use FastScroll and sticky headers library by @bgogetap, which also uses parent layout to draw views. Because of this sticky header overlaps fast scroll bubble and scrollbar.

**Proposed solution**
Add fast scroll views as a params to the listener methods, so we can call `.bringToFront()` on them.

**Comment by randr0id** [comment]
Merged.

**Comment by randr0id** [comment]
This solution will be released in 1.0.5
