### ISSUE TITLE
Bubble displaying underneath custom actionbar

### ISSUE THREAD

**Issue by tamarlehmann** [L4Digital/FastScroll#28]
Hi,

I am implementing the FastScroll for a directory/contacts style app, however, I have a custom action bar/toolbar and I can't seem to get the bubble for "a" and "b" displaying as it underneath the action bar, however, the handle stops at the bottom of the action bar. Is there a style I can override that will allow the bubble to lay on top of the handle (not have a large space between the bubble and top of the scroll handle) so it isn't hidden by the action bar?

Thanks for your help :)

**Comment by randr0id** [comment]
Hello.

It sounds like the Toolbar and FastScrollRecyclerView are children of the same ViewGroup, which might cause the issue. I typically have the Toolbar in a separate ViewGroup (usually AppBarLayout) and the bubble stops scrolling once it reaches the top of it's container.

Can you provide the xml of the layout in question so I can test? Also screenshots might be helpful if possible.
