### ISSUE TITLE
How to Hide Bubble

### ISSUE THREAD

**Issue by maracuja-juice** [L4Digital/FastScroll#29]
In my app I only want fast scroll but a bubble should not appear. Is it possible to hide it? How?

**Comment by randr0id** [comment]
I'll add an attribute/method to do this properly in the future, but for now this can be achieved by adding these dimensions to your resources:

~~~xml
<dimen name="fastscroll_bubble_size">0dp</dimen>
<dimen name="fastscroll_bubble_textsize">0sp</dimen>
<dimen name="fastscroll_bubble_padding">0dp</dimen>
~~~

**Comment by maracuja-juice** [comment]
Works like a charm.

**Comment by randr0id** [comment]
Fixed in commit 22b612c
Scheduled for release in 1.1.0

**Comment by maracuja-juice** [comment]
That new attribute is of course even better.
When will that release (approximately) be?

**Comment by randr0id** [comment]
Soon after ConstraintLayout 1.1 is released.

**Comment by maracuja-juice** [comment]
Okay good. Please update this issue when you do so.

**Comment by randr0id** [comment]
@maracuja-juice FastScroll 1.1.0 has been released. 🍻

**Comment by maracuja-juice** [comment]
@randr0id cool! I'll try it out soon in my OS app.
