### ISSUE TITLE
Got a error when building

### ISSUE THREAD

**Issue by peterforme** [L4Digital/FastScroll#3]
I use android studio to import the project, but I got a error : 
Could not get unknown property 'bintray_user' for object of type com.jfrog.bintray.gradle.BintrayExt

what went wrong?

**Comment by randr0id** [comment]
The current gradle configuration requires the properties `bintray_user` and `bintray_apikey`, which can be set to any value in `~/.gradle/gradle.properties` in order to satisfy the build.

I will push a change to make these properties optional.

**Comment by randr0id** [comment]
Fixed in commit [acf50fb](https://github.com/L4Digital/FastScroll/commit/acf50fbcf334044ca1cf08e6040bf1c8cec1fb1e)
