### ISSUE TITLE
FastScroller layout is messed up in 1.1.0

### ISSUE THREAD

**Issue by TastesLikeTurkey** [L4Digital/FastScroll#33]
I have the following layout:

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_height="match_parent"
    android:layout_width="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeLayout"
        android:layout_height="match_parent"
        android:layout_width="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_height="match_parent"
            android:layout_width="match_parent" />

    </android.support.v4.widget.SwipeRefreshLayout>

    <com.l4digital.fastscroll.FastScroller
        app:bubbleColor="?colorAccent"
        app:handleColor="?colorAccent"
        android:id="@+id/fastScroller"
        android:layout_gravity="end"
        android:layout_height="match_parent"
        android:layout_width="wrap_content"
        app:showTrack="false" />

</FrameLayout>
```

which worked fine in 1.0.4. However, after upgrading to 1.1.0 the index bubble now runs off the bottom of the screen. The track and handle also run off the bottom. In addition, the bubble is offset from the handle; it's about 50% lower. The issue is also present in 1.1.1.

![svid_20180615_084039_moment](https://user-images.githubusercontent.com/9746255/41469077-0c60a276-707a-11e8-9d09-88d60b3049a9.jpg)
![svid_20180615_084039_moment 2](https://user-images.githubusercontent.com/9746255/41469080-0e5f0694-707a-11e8-83fe-b898210c9423.jpg)

**Comment by randr0id** [comment]
Thanks for opening this issue. It's been fixed in commit f803140 and released in version 1.1.2.
