### ISSUE TITLE
Change holdable area size for the scrollbar

### ISSUE THREAD

**Issue by zunjae** [L4Digital/FastScroll#36]
On my phone, using the scrollbar is difficult because of how tiny it is. I really have to touch the edges of my phone in order to scroll properly. Is there any way to make to holdable scrollbar area bigger? I'd like to adjust the width and I can't find any documentation on doing so.

**Comment by randr0id** [comment]
You can override the handle dimensions by placing these lines in your project's `dimens.xml`, and changing the values.
~~~xml
<dimen name="fastscroll_handle_height">40dp</dimen>
<dimen name="fastscroll_handle_width">16dp</dimen>
<dimen name="fastscroll_handle_radius">8dp</dimen>
~~~
