### ISSUE TITLE
Scrollbar doesn't play nice with RecyclerView padding

### ISSUE THREAD

**Issue by hendraanggrian** [L4Digital/FastScroll#38]
Great library! Thanks for early migration to AndroidX.

In this [layout I'm working on](https://github.com/hendraanggrian/countrypicker/blob/master/countrypicker/res/layout/countrypicker.xml), my scrollbar is half-hidden when bottom padding is set to the recycler view. Changing `clipToPadding` value seem to have no effect, while removing bottom padding resolve the issue.

![screen shot 2018-11-19 at 17 31 06](https://user-images.githubusercontent.com/11507430/48701460-25f9bd80-ec21-11e8-89f1-ff608c80ff07.png)

**Comment by randr0id** [comment]
Unfortunately because of the way that FastScroller aligns itself with the RecyclerView, it cannot adjust to the padding. Instead try using `layout_marginBottom` to adjust your layout.
