### ISSUE TITLE
FastScrollRecyclerView leaks parent view

### ISSUE THREAD

**Issue by creati8e** [L4Digital/FastScroll#41]
![device-2019-04-23-115350](https://user-images.githubusercontent.com/10930232/56552757-d435d480-65be-11e9-92ef-6e55c231434b.png)
To fix crash you need to make following changes:
```
class FastScrollRecyclerView @JvmOverloads constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : FastScrollRecyclerView(context, attrs, defStyleAttr) {

    override fun onDetachedFromWindow() {
        super.onDetachedFromWindow()
        adapter = null
    }

}
```

**Comment by randr0id** [comment]
This should be handled by the same container that owns the Adapter. Most likely in the `onDestroy()` method of an Activity or Fragment

**Comment by AndroidDeveloperLB** [comment]
Why is this a leak?
The adapter is inside, and the RecyclerView holds it as usual. If the RecyclerView isn't attached, there is no more reference to it, so it can be GC-d , no?
