### ISSUE TITLE
Scroll the list the thumb never reached to the end when items are less

### ISSUE THREAD

**Issue by officialsachinverma** [L4Digital/FastScroll#42]
When I try to normally scroll the list the thumb of the  fast scroller doesn't touch end of the list, but it touched when I use thumb to scroll.

**Comment by randr0id** [comment]
Please provide an example of the layout you are using. The `ExampleActivity` in this project demonstrates that the scrolling reaches the end of the list (minus padding).

**Comment by randr0id** [comment]
Closing due to lack of details.
