### ISSUE TITLE
Ability To Adjust Handle Size

### ISSUE THREAD

**Issue by shmueldabomb441** [L4Digital/FastScroll#45]
Your library is phenomenal! On the Google Contacts app, their handle for FastScroll is much bigger than the one in your library. Can  you add an XML attribute to adjust the size? By the way, I thought you might appreciate the comment from [this SO user](https://stackoverflow.com/a/57783716/12528345) who said: "We're working with this library in production with a large user base app w/o any problem."

**Comment by shmueldabomb441** [comment]
Here is a picture of Google's handle:
![Screenshot_20201030-123238_Contacts](https://user-images.githubusercontent.com/60489781/97732118-6ec47d00-1aac-11eb-9adb-c6f44661a3bf.jpg)

**Comment by randr0id** [comment]
Hi @shmueldabomb441, thank you very much for the kind words and the link to the SO post!

You can override the handle settings by adding these attributes to your dimens.xml and modifying the values:
```
<dimen name="fastscroll_handle_height">40dp</dimen>
<dimen name="fastscroll_handle_width">4dp</dimen>
<dimen name="fastscroll_handle_radius">2dp</dimen>
```
