### ISSUE TITLE
JCenter is shutting down on May 1st, 2021

### ISSUE THREAD

**Issue by equeim** [L4Digital/FastScroll#48]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

AFAIK, currently library is available only on JCenter.

**Comment by mariolenci-hf** [comment]
Are there any news on this?

**Comment by mariolenci-hf** [comment]
It seems to be available on [Jitpack](https://jitpack.io/#L4Digital/FastScroll):

```
allprojects { repositories { maven { url 'https://jitpack.io' } } }
```

```
dependencies { implementation 'com.github.L4Digital:FastScroll:2.0.1' }
```

**Comment by randr0id** [comment]
Sorry, the relaxation on the deadline allowed more time, but I'm still planning to migrate to maven central.

**Comment by randr0id** [comment]
I decided to migrate to JitPack (already supported) due to the difficulty in verifying domain ownership and publishing. The project readme has been updated to show adding the JitPack dependency:

`project/build.grade`
```
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```

`module/build.gradle`
```
dependencies {
    implementation 'com.github.L4Digital:FastScroll:2.0.1'
}
```

**Comment by equeim** [comment]
I tried to add it like in your example, but I get AAPT errors about missing attributes. I checked Gradle cache, and for some reason it downloaded only pom file (`.gradle/cache/modules-2/files-2.1/com.github.L4Digital/FastScroll/2.0.1/7ec2e677cd1667186bd0243a8059b2c38873e38/FastScroll-2.0.1.pom`), but not aar. I use Gradle 7.0.2.

**Comment by randr0id** [comment]
I ran into the same issue. I'm in the process now of migrating to maven central.

**Comment by randr0id** [comment]
FastScroll 2.0.1 is available [on maven central now](https://repo1.maven.org/maven2/io/github/l4digital/fastscroll/2.0.1/). I'll update the README soon, but the dependency must be added as:
`implementation 'io.github.l4digital:fastscroll:2.0.1'`

**Comment by afsalb** [comment]
> 
> 
> FastScroll 2.0.1 is available [on maven central now](https://search.maven.org/artifact/io.github.l4digital/fastscroll). I'll update the README soon, but the dependency must be added as:
> `implementation "io.github.l4digital:fastscroll:2.0.1"`

i did this still im getting error.
error: package com.l4digital.fastscroll does not exist
import com.l4digital.fastscroll.FastScroller;

error: package FastScroller does not exist
        FastScroller.SectionIndexer,

**Comment by randr0id** [comment]
@afsalb You may need to clear your cache. The artifact is on maven central as can be seen from the link.
