### ISSUE TITLE
Ability to disable navigation by touch

### ISSUE THREAD

**Issue by shmueldabomb441** [L4Digital/FastScroll#55]
Sometimes I am scrolling and I by accident touch the handle track much farther down than I am currently viewing, and it skips very far down and I lose my place. Is there a way/is it possible that you can add a way to disable navigation any other way than by dragging the handle itself? If you tell me what needs to be done and where the relevant code is, I can try and make a PR, but I am very busy, so no guarantee.

**Comment by randr0id** [comment]
It's possible, but I don't think this is a feature we should support.
