### ISSUE TITLE
FastScrollRecyclerView Error

### ISSUE THREAD

**Issue by BayoKwendo** [L4Digital/FastScroll#57]
I still can't import FastScrollRecyclerView yet i have already  add 'implementation "io.github.l4digital:fastscroll:2.0.1" 

```Kotlin
cannot find symbol
    private FastScrollRecyclerView recyclerView;
```

**Comment by randr0id** [comment]
You may need to run `rm -rf ~/.gradle/caches` to reset your cached artifacts.

**Comment by randr0id** [comment]
See #48
