### ISSUE TITLE
Not supported SwipeRefreshLayout with RecyclerView

### ISSUE THREAD

**Issue by aman-jham** [L4Digital/FastScroll#7]
App is crashing when i am trying the with android.support.v4.widget.SwipeRefreshLayout as a Parent ViewGroup.

**Comment by randr0id** [comment]
`android.support.v4.widget.SwipeRefreshLayout` is not supported as a parent ViewGroup. The parent ViewGroup must be a CoordinatorLayout, FrameLayout, or RelativeLayout in order for the FastScroller to be properly displayed on top of the RecyclerView.

FastScrollRecyclerView adds the FastScroller view to the parent ViewGroup and sets the LayoutParams to align correctly with the RecyclerView. SwipeRefreshLayout can only support one direct child and therefore cannot be supported as a parent ViewGroup.

However, you could insert a FrameLayout as the direct child of the SwipeRefreshLayout:

~~~xml
<android.support.v4.widget.SwipeRefreshLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    
        <com.l4digital.fastscroll.FastScrollRecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    
    </FrameLayout>

</android.support.v4.widget.SwipeRefreshLayout>
~~~
