### ISSUE TITLE
Thickness of the thumb and customizable drawable thumb

### ISSUE THREAD

**Issue by srijanbiswas3** [L4Digital/FastScroll#88]
it would be great to increase or decrease the thickness of the thumb and also a custom drawable . 
Is it possible or can you  make it. I am not using the bubble feature so i want to customize the thumb size

**Comment by randr0id** [comment]
You can adjust the handle sizes by overriding these values in your `dimens.xml`:
```
<dimen name="fastscroll_handle_height">40dp</dimen>
<dimen name="fastscroll_handle_width">4dp</dimen>
<dimen name="fastscroll_handle_radius">2dp</dimen>
```

You might be able to replace the drawable by in including your own drawable named `fastscroll_handle`, but I haven't verified if that works.
